Trust_it/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/',  admin.site.urls),
    path('communication/',include('communication.urls')),
    path('analysisproducts/',include('analysisproducts.urls')),
    path('notification/',include('notification.urls')),
    path('maps/',include('map.urls')),
    path('', include('main.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

map/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('nokids/', views.Map_Comment_List_Nokids.as_view()),
    path('hospital/', views.Map_Review_List.as_view()),
    path('playground/', views.Map_Comment_List_Playground.as_view())
]

notification/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('create_post/', views.PostCreate.as_view()),
    path('category/<str:slug>/', views.category_page),
    path('tag/<str:slug>/', views.tag_page),
    path('<int:pk>/', views.PostDetail.as_view()),
    path('', views.PostList.as_view()),
    path('search/<str:q>/', views.PostSearch.as_view()),
]

notification/models.py
from django.db import models
from django.contrib.auth.models import User
import os



class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/notification/category/{self.slug}/'
    
    class Meta:
        verbose_name_plural="Categories"

class Tag(models.Model):
    name=models.CharField(max_length=50)
    slug=models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return f'/notification/tag/{self.slug}/'


# Create your models here.
class News(models.Model):
    title = models.CharField(max_length=30)
    hook_text = models.CharField(max_length=100, blank=True)
    content = models.TextField()

    head_image = models.ImageField(upload_to='notification/images/%Y/%m/%d/', blank=True)
    file_upload = models.FileField(upload_to='notification/files/%Y/%m/%d/', blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    # author : 추후 작성 예정
    author = models.ForeignKey(User, null = True, blank=True, on_delete=models.SET_NULL)

    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)

    tags = models.ManyToManyField(Tag, blank=True)


    def __str__(self):
        return f'[{self.pk}]{self.title}::{self.author}'
    
    def get_absolute_url(self):
         return f'/notification/{self.pk}/'
    
    def get_file_name(self):
        return os.path.basename(self.file_upload.name)
    
    def get_file_ext(self):
        return self.get_file_name().split('.')[-1]

notification/views.py
from django.shortcuts import render, redirect
from pdb import post_mortem
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.shortcuts import get_object_or_404
from .models import News, Category, Tag
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.utils.text import slugify
from django.db.models import Q
# Create your views here.

# CBV로 웹 사이트 만들기
class PostList(ListView):
    model = News
    ordering = '-pk'
    paginate_by = 7

    def get_context_data(self, **kwargs):
        context = super(PostList, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = News.objects.filter(category=None).count()
        return context

class PostDetail(DetailView):
    model = News

    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = News.objects.filter(category=None).count()
    
        return context

class PostCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = News
    fields = ['title', 'hook_text', 'content', 'head_image', 'file_upload', 'category']
    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated and (current_user.is_staff or current_user.is_superuser):
            form.instance.author = current_user
            response = super(PostCreate, self).form_valid(form)
            tags_str = self.request.POST.get('tags_str')
            if tags_str:
                tags_str = tags_str.strip()
                tags_str = tags_str.replace(',', ';')
                tags_list = tags_str.split(';')

                for t in tags_list:
                    t = t.strip()
                    tag, is_tag_created = Tag.objects.get_or_create(name=t)
                    if is_tag_created:
                        tag.slug = slugify(t, allow_unicode=True)
                        tag.save()
                    self.object.tags.add(tag)
            return response
        else:
            return redirect('/notification/')

class PostUpdate(LoginRequiredMixin, UpdateView):
    model = News
    fields = ['title', 'hook_text', 'content', 'head_image', 'file_upload', 'category']
    template_name = 'notification/post_update_form.html'

    def form_valid(self, form):
        response = super(PostUpdate, self).form_valid(form)
        self.object.tags.clear()

        tags_str = self.request.POST.get('tags_str')
        if tags_str:
            tags_str = tags_str.strip()
            tags_str = tags_str.replace(',',';')
            tags_list = tags_str.split(';')

            for t in tags_list:
                    t = t.strip()
                    tag, is_tag_created = Tag.objects.get_or_create(name=t)
                    if is_tag_created:
                        tag.slug = slugify(t, allow_unicode=True)
                        tag.save()
                    self.object.tags.add(tag)
            return response

    def get_context_data(self, **kwargs):
        context=super(PostUpdate, self).get_context_data()
        if self.object.tags.exists():
            tags_str_list = list()
            for t in self.object.tags.all():
                tags_str_list.append(t.name)
            context['tags_str_default'] = ';'.join(tags_str_list)
        return context

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(PostUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied
    
  
    
   
            
def category_page(request, slug):
    if slug == 'no_category':
        category = "미분류"
        news_list = News.objects.filter(category = None)
    else:
        category = Category.objects.get(slug=slug)
        news_list = News.objects.filter(category= category)
    return render(
        request,
        'notification/news_list.html',
        {
            'news_list' : news_list,
            'categories': Category.objects.all(),
            'no_category_news_count': News.objects.filter(category=None).count(),
            'category': category,
        }
    )
def tag_page(request, slug):
    tag = Tag.objects.get(slug=slug)
    post_list = tag.post_set.all()
    return render(
        request,
        'notification/post_list.html',
        {
            'post_list' : post_list,
            'tag' : tag,
            'categories': Category.objects.all(),
            'no_category_post_count': News.objects.filter(category=None).count(),
        }
    )


class PostSearch(PostList):
    paginate_by: None

    def get_queryset(self):
        q = self.kwargs['q']
        post_list = News.objects.filter(
            Q(title__contains=q) | Q(tags__name__contains=q)
        ).distinct()
        return post_list

    def get_context_data(self, **kwargs):
        context = super(PostSearch, self).get_context_data()
        q = self.kwargs['q']
        context['search_info']=f'Search: {q} ({self.get_queryset().count()})'
        return context

notification/templates/notification/base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <title>{% block head_title %}notification{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'notification/bootstrap/bootstrap.min.css' %}" media="screen">

    <script src="https://kit.fontawesome.com/3e7c45c38c.js" crossorigin="anonymous"></script>
</head>

<body>
    {% include 'notification/navbar.html' %}

    <section class="py-5 text-center container" style="background-color:#C9DFC0">
        <div class="row py-lg-5">
          <div class="col-lg-6 col-md-8 mx-auto">
          <h1 class="fw-light" style="color:white">TRUST_IT</h1>
            <p class="lead text-muted" style="color:white">안녕하세요<br> 믿고 쓸 수 있는 TRUST_IT 입니다</p>
          </div>
        </div>
      </section>
      <br>

    <div class="container my-3">
        <div class="row">
            <div class="col-md-8 col-lg-9" id="main-area">
                {% block main_area %}
                {% endblock %}
            </div>

            <div class="col-md-4 col-lg-3">
                <!-- Search Widget -->
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for..." id="search-input">
                    <span class="input-group-btn">
                        <button class="btn btn-secondary" type="button" onclick="searchPost()">Go!</button>
                    </span>
                </div>

                <!-- Categories Widget -->
                <div class="card my-4" id="categories-card">
                    <h5 class="card-header">Categories</h5>
                    <div class="card-body">
                        <div class="row">
                            {% for category in categories %}
                            <li style="color:rgb(102, 97, 97)"><a href="{{ category.get_absolute_url }}" style="color:black">{{category}} ({{category.news_set.count}})</a></li>
                            {% endfor %}
                            <!-- <li><a href="/notification/category/no_category/">미분류 ({{no_category_post_count}})</a></li> -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        function searchPost(){
            let searchValue = document.getElementById('search-input').value.trim();
            if(searchValue.length > 1){
                location.href = "/notification/search/" + searchValue + "/";
            }
            else{
                alert('검색어(' + searchValue + ')가 너무 짧습니다.');
            }
        };

        document.getElementById('search-input').addEventListener('keup', function(event)
        {
            if(event.key=='Enter'){
                searchPost();
            }
        });
    </script>

  {% include 'notification/footer.html' %}


    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

</body>

</html>
    

           

notification/templates/notification/base_full_width.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <title>{% block head_title %}notification{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'notification/bootstrap/bootstrap.min.css' %}" media="screen">

    <script src="https://kit.fontawesome.com/3e7c45c38c.js" crossorigin="anonymous"></script>
</head>

<body>
    {% include 'notification/navbar.html' %}
    <div class="container my-3">
        <div class="row">
            <div class="col-12" id="main-area">
                {% block main_area %}
                {% endblock %}
            </div>

        </div>
    </div>

  {% include 'notification/footer.html' %}


    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

</body>

</html>
    

           

notification/templates/notification/indexNotification.html
<!DOCTYPE html>
<html>
    {%load static%}
</html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'blog/bootstrap/bootstrap.min.css' %}" media="screen">
    <title>notification</title>
</head>
<body>
    <h1>notification</h1>

    <table>
        <thead>
            <tr class="text-center">
                <th>번호</th>
                <th>제목</th>
                <th>출처</th>
                <th>등록일</th>
            </tr>
        </thead>
        <tbody>
            <!-- {% if notice_list %} -->
            {% for p in notice_list %}
            <tr class="text-center">
                <td>{{ p.id }}</td>
                <td>{{ p.title }}</td>
                <td>{{ p.from }}</td>
                <td>{{ p.created_at }}</td>
            </tr>
            {% endfor %}
            <!-- {% else %}
            <tr class="text-center">
                <td colspan="5">
                    작성된 게시글이 없습니다.
                </td>
            </tr>
            {% endif %} -->
        </tbody>
    </table>
</body>
</html>

notification/templates/notification/navbar.html
<!DOCTYPE html>
<html>
    {%load static%}
</html>
<html lang="en">
<head>
    
    <title>{% block head_title%}TRUST_IT{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'communication/bootstrap/bootstrap.min.css' %}" media="screen">

    <script src="https://kit.fontawesome.com/1051c2b565.js" crossorigin="anonymous"></script>
    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }
  
        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }
  
        .b-example-divider {
          height: 3rem;
          background-color: rgba(0, 0, 0, .1);
          border: solid rgba(0, 0, 0, .15);
          border-width: 1px 0;
          box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }
  
        .b-example-vr {
          flex-shrink: 0;
          width: 1.5rem;
          height: 100vh;
        }
  
        .bi {
          vertical-align: -.125em;
          fill: currentColor;
        }
  
        .nav-scroller {
          position: relative;
          z-index: 2;
          height: 2.75rem;
          overflow-y: hidden;
        }
  
        .nav-scroller .nav {
          display: flex;
          flex-wrap: nowrap;
          padding-bottom: 1rem;
          margin-top: -1px;
          overflow-x: auto;
          text-align: center;
          white-space: nowrap;
          -webkit-overflow-scrolling: touch;
        }
        body {
        padding-top: 75px;
        }
      </style>
      <link href="navbar-top-fixed.css" rel="stylesheet">
</head>
<body>
    
  <nav class="navbar navbar-expand-md navbar-light fixed-top bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="">TRUST IT</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/notification/">Notification</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/communication/">Community</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/maps/nokids/">Map</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/analysisproducts/">Ingredients</a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="#" data-toggle="modal" data-target="#loginModal">Log In&emsp;&emsp;&emsp;</a>
            </li>
        </ul>
      </div>
    </div>
  </nav>
  
  <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="logInModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="loginModalLabel"> <i class="fas fa-sign-in-alt"></i>&nbsp Log In</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-6">
                            <button type="button" class="btn btn-outline-dark btn-block btn-sm "><i
                                    class="fab fa-google"></i>&nbsp&nbsp Log in with Google</button>
                            <button type="button" class="btn btn-outline-dark btn-block btn-sm "><i
                                    class="far fa-envelope"></i>&nbsp&nbsp Log in with E-mail</button>
                        </div>
                        <div class="col-md-6">
                            <button type="button" class="btn btn-outline-dark btn-block btn-sm"><i
                                    class="far fa-envelope"></i>&nbsp&nbsp Sign Up with E-mail</button>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

notification/templates/notification/news_detail.html
{% extends 'notification/base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}
    {{ news.title }} - notification
{% endblock %}

{% block main_area %}
    <div id="post-area">
        {% if news.category %}
        <span class="badge badege-secondary float-right">{{ news.category }}</span>
        {% else %}
        <span class="badge badge-secondary float-right">미분류</span>
        {% endif %}
        <!-- Title -->
        <h1 class="mt-4">{{ news.title }}
        <!-- <h5 class="text-muted">{{ news.hook_text }}</h5> -->

        <!-- Author -->
      
         
            <i href="#" style="font-size:12px;"> from{{ news.author | upper}}</i>
      
        </h1>
        <hr>
        <!-- {% if user.is_authenticated and user == post.author %}
            <a class="btn btn-info btn-sm float-right" role="button" href="/notification/update_post/{{post.pk}}/">
                <i class="fas fa-pen"></i>Edit Post
            </a>
        {% endif %} -->
        <!-- Date/Time -->
        <p>{{ news.created_at }}</p>

        <hr>

        <!-- Preview Image -->
        <!-- {% if post.head_image %}
        <img class="img-fluid rounded" src="{{ post.head_image.url }}" alt="{{post.title}} head_image">
        {% else %}
        <img class="img-fluid rounded" src="https://picsum.photos/seed/{{p.id}}/800/200" alt="random_image">
        {% endif %}
        <hr> -->

        <!-- Post Content -->
        <p>{{ news.content | linebreaks }}</p>
        <!-- {% if post.tags %}
            <i class="fas fa-tags"></i>
            {% for tag in post.tags.all %}
                <a href="{{ tag.get_absolute_url }}" class="badge rounded-pill bg-primary">
                    {{ tag }}
                </a>
            {% endfor %}
            <br/><br/>
        {% endif %} -->
        {% if news.file_upload %}
        <a href="{{ news.file_upload.url }}" class="btn btn-primary" role="button" download>Download

            {% if news.get_file_ext == 'csv' %}
            <i class="fas fa-file-csv"></i>
            {% elif news.get_file_ext == 'xlsx' or news.get_file_ext == 'xls' %}
            <i class="fas fa-file-exel"></i>
            {% elif news.get_file_ext == 'docx' or news.get_file_ext == 'doc' %}
            <i class="fas fa-file-word"></i>
            {% else %}
            <i class="fas fa-file"></i>
            {% endif %}

            {{ news.get_file_name }}
        </a>
        {% endif %}
        <hr>
    </div>

{% endblock %}

notification/templates/notification/news_list.html
{% extends 'notification/base.html' %}  
{% block main_area %} 
    <head>
        <style>
            table {
                width: 100%;
                border-top: 1px solid #444444;
                border-collapse: collapse;
            }
            th, td {
                border-bottom: 1px solid #444444;
                padding: 10px;
            }
            #post_title{
                color:#7B7473;
                text-decoration:none;
            }
            #post_title:visited {
                color : black;
                text-decoration: none;
            }
            #post_title:hover {
                color : red;
                text-decoration: underline;
            }
            #post_title:active {
                color : green;
                text-decoration: none;
            }
          </style>
    </head>
        <h1>공지
            {% if search_info %}<small class="text-muted">{{ search_info }}</small>{%endif%}
            {% comment %} {% if category %} <span class="badge bg-secondary">{{category}}</span>{%endif%} {% endcomment %}
            {% if tag %}<i class="fas fa-tags"></i> <span class="badge rounded-pill bg-primary">{{tag}}</span>{%endif%}</h1>
            {% if news_list %}
            <br>
            <table>
                <thead>
                    <tr class="text-center">
                        <th class="number" style="width:50px;" >번호</th>
                        <th style="width:200px">제목</th>
                        <th style="width:50px">출처</th>
                        <th style="width:200px">작성일</th>
                        <!-- <th style="width:100px">태그</th> -->
                    </tr>
                </thead>
                <tbody>
                {% for p in news_list %}
                <!-- Blog Post -->
                <tr class="text-center">
                    <td>{{ p.id }}</td>
                    <td><a id="post_title" href="{{ p.get_absolute_url }}">{{ p.title }}</a></td>
                    <td>{{ p.author }}</td>
                    <td>{{ p.created_at }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
            {% else %}
                <br><h3>아직 게시물이 없습니다</h3>
            {% endif %}
            {% if is_paginated %}
            <br><br>
            <!-- Pagination -->
            <ul class="pagination justify-content-center mb-4">
                <!--최근 근 존재 o : Newer 버튼 활성화 -->
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&larr; 이전 </a>
                    </li>
                <!--최근 근 존재 x : Newer 버튼 비활성화 -->
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#">&larr; 이전 </a>
                    </li>
            {% endif %}

                <!--오래된 글 존재 o : Older 버튼 활성화-->
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">다음 &rarr;</a>
                    </li>
                <!--오래된 글 존재 x : Older 버튼 비활성화-->
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#">&larr; 다음 &rarr;</a>
                    </li>
                {% endif %}

            </ul>
            {% endif %}
{% endblock %}